---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "{{ $.Release.Name }}.{{ .Values.url }}"
  gateways:
  - {{ $.Release.Name }}
  - mesh
  http:
    - route:
      - destination:
          host: {{ $.Release.Name }}.{{ .Values.namespace }}.svc.cluster.local
          port:
            number: 80
      corsPolicy:
        allowMethods:
          - GET
          - POST
          - OPTIONS
        allowOrigins:
          - exact: "*"
        allowHeaders:
          - "access-control-allow-origin"
        allowCredentials: true
