---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraPortMappings:
  # Istio HTTP
  - containerPort: 30080
    hostPort: 8080
  # Istio HTTPS
  - containerPort: 30443
    hostPort: 8443
  # Istio status port
  - containerPort: 31521
    hostPort: 31521
  # Envoy example nodeport
  - containerPort: 31080
    hostPort: 8081
- role: worker
